name: CJ Hospital Alert

on:
  schedule:
    - cron: '0 0 * * *' # 매일 한국시간 오전 9시 실행
  workflow_dispatch: # 직접 실행 버튼 생성

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script
        run: python hospital.py
        env:
          DATA_API_KEY: ${{ secrets.DATA_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
